id: IFFDEAFED
legacy_id: P005461
ocr_import_info:
  bdrc_scan_id: W1KG14555
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T01:44:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:05:40.382943+00:00'
last_modified: 2022-08-27 13:06:26.971163
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14555
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14555
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་སྤྱོད་ཐེག་མཆོག་འཇུག་ངོགས།
statistics:
  ocr_word_mean_confidence_index: 0.9383197369527995
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG14573:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14573
      total_pages: 556
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14573.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9383197369527995
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
